apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: product-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: 687450791434.dkr.ecr.ap-south-1.amazonaws.com/java-service:62  
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.shared-db.svc.cluster.local:3306/product_catalogue
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: product-latest
spec:
  selector:
    app: product-api
  ports:
    - port: 80
      targetPort: 8000
