apiVersion: v1
kind: Namespace
metadata:
  name: shared-db

---
apiVersion: storage.k8s.io/v1         # ✅ corrected group
kind: StorageClass
metadata:
  name: mysql-sc                      # 👈 custom name is fine
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer  # ✅ spelling was wrong (sneaky camelCase trap)

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: shared-db
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: shared-db
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: shared-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: product_catalogue
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
