apiVersion: v1
kind: Namespace
metadata:
  name: shared-db
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-v1
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-v1-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-v2